# CODEX PROMPT

## 유튜브 공식 문서 링크

유투브 공식 문서 링크인데, 이걸 참고해서 유투브 데이터를 수집하고 싶어.

검색어를 변수로 만들어주고, 해당 영상 수집과, 영상 상세 정보 수집을 아래 api참고해서 코드를 작성해줘.

환경변수의 파일경로는 C:\Users\Playdata\Desktop\김동석\파이썬 학습\enkoa-practice-python\day05_데이터수집\데이터_수집_1_API_실습파일\day05_데이터수집\데이터_수집_1_API_실습파일\.env

작업해야하할 코드 파일 경로는 C:\Users\Playdata\Desktop\김동석\파이썬 학습\enkoa-practice-python\day05_데이터수집\데이터_수집_1_API_실습파일\day05_데이터수집\데이터_수집_1_API_실습파일\3_유투브_API 실습.ipynb

[공식문서](https://developers.google.com/youtube/v3/docs/search/list?hl=ko&_gl=1*1kqhs8p*_up*MQ..*_ga*MTM2ODc4NDY2Ny4xNzg0Nzc3OTg2*_ga_SM8HXJ53K2*czE3ODQ3Nzc5ODUkbzEkZzAkdDE3ODQ3Nzc5OTIkajUzJGwwJGgw)

[공식문서](https://developers.google.com/youtube/v3/docs/videos/list?hl=ko&_gl=1*1kqhs8p*_up*MQ..*_ga*MTM2ODc4NDY2Ny4xNzg0Nzc3OTg2*_ga_SM8HXJ53K2*czE3ODQ3Nzc5ODUkbzEkZzAkdDE3ODQ3Nzc5OTIkajUzJGwwJGgw)

## YouTube Video Search

### 0. Load Environment Variables

In [21]:
import os
from pathlib import Path

from dotenv import load_dotenv

env_path = Path(".env")
load_dotenv(env_path)

YOUTUBE_API_KEY = os.getenv("YOUTUBE_API_KEY")

if not YOUTUBE_API_KEY:
    raise ValueError(f"YOUTUBE_API_KEY was not found. Check this file: {env_path.resolve()}")

### 1. Search Videos with `search/list`

In [22]:
import pandas as pd
import requests

search_url = "https://www.googleapis.com/youtube/v3/search"

query = "메이플육성", "메이플 가이드", "하이퍼버닝"
max_results = 100

In [23]:
search_params = {
    "part": "snippet",
    "q": query,
    "type": "video",
    "maxResults": max_results,
    "key": YOUTUBE_API_KEY,
}

search_response = requests.get(search_url, params=search_params)
search_response.raise_for_status()
search_data = search_response.json()

search_items = []
for item in search_data.get("items", []):
    snippet = item.get("snippet", {})
    video_id = item.get("id", {}).get("videoId")
    if not video_id:
        continue

    search_items.append(
        {
            "video_id": video_id,
            "title": snippet.get("title"),
            "channel_title": snippet.get("channelTitle"),
            "published_at": snippet.get("publishedAt"),
            "description": snippet.get("description"),
        }
    )

search_df = pd.DataFrame(search_items)
display(search_df)

,video_id,title,channel_title,published_at,description
0,mQo4xmzyIgY,[메이플] 하이퍼 버닝🌸 뉴비들을 위한! 아이템 버닝의 🐳한계는 있다?! 전투력 1...,잼이,2026-08-11T09:51:45Z,메이플 #메이플스토리 #잼이 #하이퍼버닝 #챌린저스 #아이템버닝 #여름방학 #겨울방...
1,1ArZ9wfeyqA,[메이플] 2026년 최신! 봄방학 🌸 뉴비들과 복귀 형님들을 위한🐧 하이퍼 버닝 ...,잼이,2026-03-18T08:18:12Z,메이플 #메이플스토리 #잼이 #하이퍼버닝 #챌린저스 #아이템버닝 #겨울방학 #크라운...
2,qc3mKB8uiSA,하이퍼버닝 단 1시간 컷 보여드리겠습니다,글자네,2025-10-02T08:35:23Z,항상 영상 사랑해주셔서 감사합니다! 세글자 팬카페 : https://cafe.nav...
3,6RGKFGjff3k,신직업 레테 하이퍼버닝 단 30분 컷 보여드리겠습니다,글자네,2026-06-21T09:15:26Z,항상 영상 사랑해주셔서 감사합니다! 세글자의 모든것 : https://linktr....
4,4aujILjlhkE,"필요 경험치가 반토막난 23주년 하버, 언제 어떻게 키워야할까?【메이플】",지명,2026-03-16T03:00:00Z,지명 #메이플 #23주년 #하이퍼버닝 지명 치지직 : https://chzzk.na...
5,FMUmSNtWlEU,[메이플] 2026년 🐳여름방학! 하이퍼 버닝🌸 뉴비들을 위한! 맨땅 1렙부터📈 스...,잼이,2026-06-17T08:27:13Z,메이플 #메이플스토리 #잼이 #하이퍼버닝 #챌린저스 #아이템버닝 #여름방학 #겨울방...
6,9b-cCrQyKYw,[한자] 하이퍼버닝 +하이퍼블링크 시작 전 마지막 점검!!! (놓치는 것 없이 세팅...,한자,2026-06-18T00:28:46Z,메이플스토리 하이퍼버닝 + 하이퍼블링크 완벽 가이드! 단 20~30분 만에 260레...
7,GeniNYE0V5M,[메이플] 2026년 최신! 하이퍼 버닝🌸 뉴비들을 위한! 고인물이 가르쳐 주지 않...,잼이,2026-08-05T12:16:03Z,메이플 #메이플스토리 #잼이 #하이퍼버닝 #챌린저스 #아이템버닝 #여름방학 #겨울방...
8,ytnhqWf3_nQ,[메이플] 하이퍼 버닝 🌸 비수기 뉴비 유저들을 위한! 뉴비가 해야하는 🌷 270레...,잼이,2026-04-17T09:11:14Z,메이플 #메이플스토리 #잼이 #하이퍼버닝 #챌린저스 #아이템버닝 #겨울방학 #크라운...
9,9saj1Kg7S1I,[메이플] 하이퍼 버닝 🌸 뉴비들을 위해서! 아이템 버닝 D-day 40 🐳 마지막...,잼이,2026-08-07T11:55:20Z,메이플 #메이플스토리 #잼이 #하이퍼버닝 #챌린저스 #아이템버닝 #여름방학 #겨울방...
10,rEMZwLbgmcw,[메이플] 하이퍼 버닝 🌸뉴비들을 위해서! 챌린저스 D-day 50일! 남은 기간 ...,잼이,2026-07-29T10:18:59Z,메이플 #메이플스토리 #잼이 #하이퍼버닝 #챌린저스 #아이템버닝 #여름방학 #겨울방...
11,E10ZLrIvvLU,메이플스토리 하이퍼버닝 유튜버 동시 반응 + 자막,쵸코릴리,2022-06-15T10:11:29Z,"특정 유튜버에 대한 욕설, 비하, 모욕 등 부적절한 댓글은 삭제됩니다."
12,QaxJ3yyFKLU,[메이플] 2026년 최신! 하이퍼 버닝🌸 뉴비들을 위한! 사람은 마음이 원동력💞 ...,잼이,2026-05-15T10:02:15Z,메이플 #메이플스토리 #잼이 #하이퍼버닝 #챌린저스 #아이템버닝 #여름방학 #겨울방...
13,WD11kJwi7qk,[메이플] 여름방학 🐳 하이퍼 버닝🌸 뉴비들을 위한! 지금 챌섭해도 되나요? 늦게 ...,잼이,2026-07-17T08:41:29Z,메이플 #메이플스토리 #잼이 #하이퍼버닝 #챌린저스 #아이템버닝 #여름방학 #겨울방...
14,hpCNPwUH3Xs,&quot;오직 성능으로만 뽑았습니다&quot; - 메이플 하이퍼버닝 직업 추천,도루,2025-12-16T10:05:04Z,메이플 메이플 하이퍼버닝 직업 추천.
15,bvjkNF-9wGA,직업 선택하기 전 꼭 보세요. / 본인에게 잘 맞는 직업을 선택하는 방법,슈크림메이플,2026-06-11T09:34:21Z,메이플스토리 #하이퍼버닝 #직업선택 저는 미하일을 키우려는 메린이에여. ​ 왜 그런...
16,I_Xv18kwQOk,하이퍼버닝부스터 직업추천 TOP3. 유니온용 / 부캐용 각각 추천해드립니다,메이플 대장메린이,2025-08-24T03:00:31Z,출석보상으로 받는 하이퍼 버닝 부스터 사용할 직업 추천입니다 유니온용 TOP3와 보...
17,AZJBul4Yu28,서버선택 + 레벨업 + 템셋팅까지 모두 담았습니다! 2차 하이퍼버닝 육성 핵심 가이드,물다이아,2025-08-21T08:00:11Z,메이플 #하이퍼버닝 #물다이아 BGM 정보 로스트사가 - 큐브 블럭 타임라인 00:...
18,DjPrjex0M8o,[메이플] 잼이님 캐릭터가 🤖 빈 깡통입니다..하이퍼 버닝 MAX 부스터🔥 빈깡통 ...,잼이,2026-03-20T07:04:27Z,메이플 #메이플스토리 #잼이 #하이퍼버닝 #챌린저스 #아이템버닝 #겨울방학 #크라운...
19,nEgGNUhzcSY,하이퍼버닝 단 4시간 컷 보여드리겠습니다,글자네,2024-07-03T11:00:20Z,항상 영상 사랑해주셔서 감사합니다! 세글자 팬카페 : https://3gj.kr/ ...
20,Q-b20FJZ0jQ,[메이플스토리 맑음] 챌린저스 월드 공략! (시즌4) / 260레벨 30분컷 빌드 ...,메이플스토리맑음,2026-06-17T05:05:10Z,챌린저스월드공략 #하이퍼버닝맥스 #챌린저스월드 #챌린저스월드3만점공략 #챌린저스월드...
21,pgibyVx8B1E,하이퍼버닝 꿀직업들 모두 정리했습니다. 손해보기 싫으시다면 보세요.,슈크림메이플,2026-04-02T10:33:00Z,메이플스토리 #일리움 #렌 #와헌 #보마 #직업추천 #메이플스토리 이번 영상에서는 ...
22,ODlGzZkGAKw,제로 하이퍼 버닝 아직 할만해? (육성가이드라인),박서월,2024-12-16T21:30:02Z,AI로 자막달다보니 자막 오류가 만져도 조금씩 놓치네용 ㅠ 썸넬도 대충 하다 마는편...
23,JnpdwKKke5Y,챌섭 국밥직업 4황 [메이플스토리 챌린저스월드 하이퍼버닝 추천직업],슈크림메이플,2026-05-23T02:15:56Z,메이플스토리 #챌린저스월드 #하이퍼버닝 메이플에서 새로운 직업을 키울때 가장 좋은것...
24,2W6Xpq_0WcM,[한자] 현재 하이퍼버닝 추천 직업과 비추천 직업 정리 (25년 12월 기준 챌섭 ...,한자,2025-12-11T07:16:56Z,하이하이 한자입니다~S2 이제 곧 하이퍼버닝 시즌이 옵니다 ㅎㅎ 항상 하는 그 고민...
25,le-wd0DnnVw,[메이플스토리] 너가 뭘 좋아할 지 몰라 전부 준비해봤어「2026년 여름 하이퍼버닝...,햄군 Youtube,2026-06-09T11:42:08Z,메이플스토리 #메이플 #하이퍼버닝 #직업추천 #렌 #보우마스터 #와일드헌터 #윈드브...
26,abNb5OJJQdw,[메이플] 2026년 최신! 하이퍼 버닝🌸 뉴비들을 위한! 사스케는 📈 웃고 있다...,잼이,2026-05-08T10:45:20Z,메이플 #메이플스토리 #잼이 #하이퍼버닝 #챌린저스 #아이템버닝 #여름방학 #겨울방...
27,rhFbqj9QPEY,찐 메린이분들도 따라하기 쉽도록 만들어보았습니다! 빠르게 육성하고 싶으시다면 따라하세요!,슈크림메이플,2026-06-21T05:58:05Z,챌린저스월드 #하이퍼버닝 #메이플스토리 이번 영상에서는 10레벨부터 280레벨까지 ...
28,5C5DU2FiHZk,하이퍼버닝 직업 선택 전이라면 이 직업들 추천합니다 / 메이플스토리 직업추천,브하,2026-06-05T07:45:32Z,곧 있으면 메이플스토리의 하이퍼버닝이 시작됩니다. 이번엔 어떤 것을 키울지 정하셨나...
29,mMrZcNy4rxM,[메이플] 하이퍼 버닝 뉴비들을 위한! 잼이가 발로 해도 되는?! 쉬운 캐릭터 TOP 5,잼이,2026-05-27T11:50:59Z,메이플 #메이플스토리 #잼이 #하이퍼버닝 #챌린저스 #아이템버닝 #여름방학 #겨울방...
30,GHZjxf6SGGk,[메이플] 2026년 🌸 최신! 하이퍼 버닝 🌷 뉴비 필수 시청! 이거 안키우면 📈...,잼이,2026-04-06T08:31:04Z,메이플 #메이플스토리 #잼이 #하이퍼버닝 #챌린저스 #아이템버닝 #겨울방학 #크라운...
31,Mk8vWAocenE,어디서도 본 적 없는 하이퍼버닝 육성 꿀팁 [메이플],혜유안,2026-03-17T06:15:10Z,생방송 유튜브 https://www.youtube.com/@user-qh6js3nw...
32,LwHvINCLuvI,[메이플] 하이퍼 버닝 🌸 뉴비들을 위한! 노말 메이린만 잡으면 된다? 챌린저스 📈...,잼이,2026-06-24T08:43:08Z,메이플 #메이플스토리 #잼이 #하이퍼버닝 #챌린저스 #아이템버닝 #여름방학 #겨울방...
33,Jg9xSIh9-ls,하이퍼버닝 사냥터부터 기초 템셋팅 방법까지 한번에! 메이플 챌린저스 월드 시즌4 핵...,물다이아,2026-06-14T00:00:37Z,챌섭 #챌린저스 #메이플 #물다이아 BGM 정보 로스트사가 - 큐브블럭 타임라인 0...
34,T61RzWvrU2g,직접 키워보고 추천하는 하이퍼 버닝 직업 추천! [메이플],혜유안,2025-12-12T06:49:35Z,생방송 유튜브 https://www.youtube.com/@user-qh6js3nw...
35,OgDvqNAM4ts,[메이플] 2026년 최신! 봄방학🌸 뉴비들을 위한! 하이퍼 버닝 🔥 MAX 캐릭터...,잼이,2026-03-23T09:05:54Z,메이플 #메이플스토리 #잼이 #하이퍼버닝 #챌린저스 #아이템버닝 #겨울방학 #크라운...
36,p8YeYncyJvc,[메이플] 하이퍼 버닝🌸 뉴비들을 위한! 이걸로 대체 되나요? 뉴비들이 🌷물어보는 ...,잼이,2026-05-29T11:33:48Z,메이플 #메이플스토리 #잼이 #하이퍼버닝 #챌린저스 #아이템버닝 #여름방학 #겨울방...
37,znHtKkHPvEQ,[메이플]하이퍼 버닝 🌸뉴비들을 위한! 재미 VS 체급? 본캐를 고를때💪 살펴봐야하...,잼이,2026-05-25T11:33:25Z,메이플 #메이플스토리 #잼이 #하이퍼버닝 #챌린저스 #아이템버닝 #여름방학 #겨울방...
38,Z9YUl3yQhxU,뉴비도 따라할 수 있도록 만들어봤습니다! 하이퍼버닝 최단시간 육성빌드,슈크림메이플,2025-06-22T11:06:42Z,메이플스토리 #하이퍼버닝 #260 #270 #사냥터 이번 영상에서는 부담없이 보면서...
39,TiyVva-odH0,[메이플스토리] &quot;슈프림 유니온 랭커&quot;가 엄선한「2025년 겨울 ...,햄군 Youtube,2025-12-15T12:52:11Z,메이플스토리 #메이플 #하이퍼버닝 #직업추천 #팔라딘 #렌 #썬콜 #배틀메이지 #일...
40,Yd-UNV3RbfM,"완전 쌩 무자본 아델 육성 1화 (챌린저스 월드, 아이템 버닝, 하이퍼 버닝 MAX)",개구릿대,2025-12-19T05:45:02Z,무과금 육성기 레벨이 한번에 5씩 오르는 대박 메이플스토리 겨울방학 이벤트의 시작!...
41,spAIOQ2nBZs,[한자] 2026년 여름 오버드라이브 하이퍼버닝 최종 직업추천 총정리!! (메잘알 ...,한자,2026-06-17T03:08:16Z,"2026년 여름, '오버드라이브' 하이퍼버닝! 어떤 직업을 키울지 아직도 고민 중이..."
42,Dl6JGFAfczE,[메이플] 하이퍼 버닝에 &#39;이 직업&#39; 주면📈 100% 폐사합니다. 본...,잼이,2026-04-29T10:50:49Z,메이플 #메이플스토리 #잼이 #하이퍼버닝 #챌린저스 #아이템버닝 #겨울방학 #크라운...
43,hkQYIrPbthM,"[메이플] 봄 소풍🌸 뉴비들을 위한! NO 아이템 버닝, NO 자본🧹 맨땅 캐릭터 ...",잼이,2026-04-01T08:35:28Z,메이플 #메이플스토리 #잼이 #하이퍼버닝 #챌린저스 #아이템버닝 #겨울방학 #크라운...
44,ep6YvyuVbV0,[메이플] 2026년 최신! 하이퍼 버닝🌸 뉴비들을 위한! 뉴비면 꼭 봐야하는📈 4...,잼이,2026-06-08T14:37:07Z,메이플 #메이플스토리 #잼이 #하이퍼버닝 #챌린저스 #아이템버닝 #여름방학 #겨울방...
45,Jw0QMbJDWm0,[한자] 하이퍼버닝 MAX 고효율 초고속 육성 방법 (25년 겨울 크라운 하이퍼버닝...,한자,2025-12-15T04:33:01Z,"이번 25년 겨울 '크라운' 하이퍼버닝, 챌린저스 월드에서 시작하시나요? 생성 보상..."
46,f92dfu0biJI,260이후 메린이 해야할일 완벽정리.필수내실과 템세팅까지[메이플스토리],메이플 대장메린이,2026-06-19T04:29:41Z,0:00 인트로 0:13 버닝비욘드 0:18 제네시스퀘스트 0:24 선행퀘스트 0:...
47,HVSa7aqX5Tk,나로후닝의 2026 여름 직업 추천&amp;평가,후닝,2026-06-10T08:00:04Z,메이플 #나로후닝 #직업추천 #하이퍼버닝 00:00 인트로 00:31 제논 04:2...
48,4KtXVKyIBaM,[한자] 23주년 이벤트 직접 보여주는 공략 (하이퍼버닝 + 영구 자석펫 + 보약스...,한자,2026-03-15T20:57:53Z,3월 19일(목) 업데이트되는 23주년 이벤트! 랜선투어에서 예고했던 내용들이 인게...
49,SwkChr520Lg,「2026 최신 버전」메이플스토리 하버 직업 추천,페이지,2026-03-27T23:36:16Z,메이플 #하이퍼버닝 #직업추천 ▷ 구독과 좋아요는 제작자에게 큰 힘이 됩니다. ▷ ...

### 2. Get Video Details with `videos/list`

In [24]:
videos_url = "https://www.googleapis.com/youtube/v3/videos"

In [25]:
video_ids = search_df["video_id"].tolist()

videos_params = {
    "part": "snippet,statistics,contentDetails",
    "id": ",".join(video_ids),
    "key": YOUTUBE_API_KEY,
}

videos_response = requests.get(videos_url, params=videos_params)
videos_response.raise_for_status()
video_data = videos_response.json()

video_items = []
for item in video_data.get("items", []):
    snippet = item.get("snippet", {})
    statistics = item.get("statistics", {})
    content_details = item.get("contentDetails", {})

    video_items.append(
        {
            "video_id": item.get("id"),
            "video_title": snippet.get("title"),
            "category_id": snippet.get("categoryId"),
            "duration": content_details.get("duration"),
            "view_count": statistics.get("viewCount"),
            "like_count": statistics.get("likeCount"),
            "comment_count": statistics.get("commentCount"),
        }
    )

video_df = pd.DataFrame(video_items)
display(video_df)

,video_id,video_title,category_id,duration,view_count,like_count,comment_count
0,mQo4xmzyIgY,[메이플] 하이퍼 버닝🌸 뉴비들을 위한! 아이템 버닝의 🐳한계는 있다?! 전투력 1...,20,PT8M28S,10217,88,55
1,1ArZ9wfeyqA,[메이플] 2026년 최신! 봄방학 🌸 뉴비들과 복귀 형님들을 위한🐧 하이퍼 버닝 ...,20,PT10M4S,120347,839,415
2,qc3mKB8uiSA,하이퍼버닝 단 1시간 컷 보여드리겠습니다,20,PT14M47S,206692,845,95
3,6RGKFGjff3k,신직업 레테 하이퍼버닝 단 30분 컷 보여드리겠습니다,20,PT14M5S,155762,621,79
4,4aujILjlhkE,"필요 경험치가 반토막난 23주년 하버, 언제 어떻게 키워야할까?【메이플】",20,PT7M15S,139680,1074,309
5,FMUmSNtWlEU,[메이플] 2026년 🐳여름방학! 하이퍼 버닝🌸 뉴비들을 위한! 맨땅 1렙부터📈 스...,20,PT12M15S,84714,727,144
6,9b-cCrQyKYw,[한자] 하이퍼버닝 +하이퍼블링크 시작 전 마지막 점검!!! (놓치는 것 없이 세팅...,20,PT7M2S,53814,317,46
7,GeniNYE0V5M,[메이플] 2026년 최신! 하이퍼 버닝🌸 뉴비들을 위한! 고인물이 가르쳐 주지 않...,20,PT8M13S,9593,123,40
8,ytnhqWf3_nQ,[메이플] 하이퍼 버닝 🌸 비수기 뉴비 유저들을 위한! 뉴비가 해야하는 🌷 270레...,20,PT10M4S,50606,362,154
9,9saj1Kg7S1I,[메이플] 하이퍼 버닝 🌸 뉴비들을 위해서! 아이템 버닝 D-day 40 🐳 마지막...,20,PT10M27S,19821,181,88
10,rEMZwLbgmcw,[메이플] 하이퍼 버닝 🌸뉴비들을 위해서! 챌린저스 D-day 50일! 남은 기간 ...,20,PT8M3S,31012,179,117
11,E10ZLrIvvLU,메이플스토리 하이퍼버닝 유튜버 동시 반응 + 자막,20,PT1M3S,370337,2277,265
12,QaxJ3yyFKLU,[메이플] 2026년 최신! 하이퍼 버닝🌸 뉴비들을 위한! 사람은 마음이 원동력💞 ...,20,PT10M58S,29569,103,50
13,WD11kJwi7qk,[메이플] 여름방학 🐳 하이퍼 버닝🌸 뉴비들을 위한! 지금 챌섭해도 되나요? 늦게 ...,20,PT9M43S,19677,202,49
14,hpCNPwUH3Xs,"""오직 성능으로만 뽑았습니다"" - 메이플 하이퍼버닝 직업 추천",20,PT12M16S,186912,859,369
15,bvjkNF-9wGA,직업 선택하기 전 꼭 보세요. / 본인에게 잘 맞는 직업을 선택하는 방법,20,PT10M17S,50730,180,200
16,I_Xv18kwQOk,하이퍼버닝부스터 직업추천 TOP3. 유니온용 / 부캐용 각각 추천해드립니다,20,PT57S,182032,567,120
17,AZJBul4Yu28,서버선택 + 레벨업 + 템셋팅까지 모두 담았습니다! 2차 하이퍼버닝 육성 핵심 가이드,20,PT15M14S,132593,1370,448
18,DjPrjex0M8o,[메이플] 잼이님 캐릭터가 🤖 빈 깡통입니다..하이퍼 버닝 MAX 부스터🔥 빈깡통 ...,20,PT9M43S,61608,476,175
19,nEgGNUhzcSY,하이퍼버닝 단 4시간 컷 보여드리겠습니다,20,PT11M6S,930919,3080,267
20,Q-b20FJZ0jQ,[메이플스토리 맑음] 챌린저스 월드 공략! (시즌4) / 260레벨 30분컷 빌드 ...,20,PT28M34S,594141,5329,414
21,pgibyVx8B1E,하이퍼버닝 꿀직업들 모두 정리했습니다. 손해보기 싫으시다면 보세요.,20,PT10M12S,83155,212,252
22,ODlGzZkGAKw,제로 하이퍼 버닝 아직 할만해? (육성가이드라인),20,PT6M33S,66488,493,174
23,JnpdwKKke5Y,챌섭 국밥직업 4황 [메이플스토리 챌린저스월드 하이퍼버닝 추천직업],20,PT11M46S,47363,174,279
24,2W6Xpq_0WcM,[한자] 현재 하이퍼버닝 추천 직업과 비추천 직업 정리 (25년 12월 기준 챌섭 ...,20,PT8M45S,85768,207,173
25,le-wd0DnnVw,[메이플스토리] 너가 뭘 좋아할 지 몰라 전부 준비해봤어「2026년 여름 하이퍼버닝...,20,PT26M55S,79135,356,334
26,abNb5OJJQdw,[메이플] 2026년 최신! 하이퍼 버닝🌸 뉴비들을 위한! 사스케는 📈 웃고 있다...,20,PT9M39S,51407,135,83
27,rhFbqj9QPEY,찐 메린이분들도 따라하기 쉽도록 만들어보았습니다! 빠르게 육성하고 싶으시다면 따라하세요!,20,PT11M26S,49205,476,74
28,5C5DU2FiHZk,하이퍼버닝 직업 선택 전이라면 이 직업들 추천합니다 / 메이플스토리 직업추천,20,PT10M11S,64863,506,254
29,mMrZcNy4rxM,[메이플] 하이퍼 버닝 뉴비들을 위한! 잼이가 발로 해도 되는?! 쉬운 캐릭터 TOP 5,20,PT8M59S,20817,93,108
30,GHZjxf6SGGk,[메이플] 2026년 🌸 최신! 하이퍼 버닝 🌷 뉴비 필수 시청! 이거 안키우면 📈...,20,PT10M48S,51302,388,67
31,Mk8vWAocenE,어디서도 본 적 없는 하이퍼버닝 육성 꿀팁 [메이플],20,PT2M25S,31937,327,152
32,LwHvINCLuvI,[메이플] 하이퍼 버닝 🌸 뉴비들을 위한! 노말 메이린만 잡으면 된다? 챌린저스 📈...,20,PT10M35S,46541,395,138
33,Jg9xSIh9-ls,하이퍼버닝 사냥터부터 기초 템셋팅 방법까지 한번에! 메이플 챌린저스 월드 시즌4 핵...,20,PT18M10S,212336,3743,690
34,T61RzWvrU2g,직접 키워보고 추천하는 하이퍼 버닝 직업 추천! [메이플],20,PT13M46S,82504,262,164
35,OgDvqNAM4ts,[메이플] 2026년 최신! 봄방학🌸 뉴비들을 위한! 하이퍼 버닝 🔥 MAX 캐릭터...,20,PT9M11S,56875,161,135
36,p8YeYncyJvc,[메이플] 하이퍼 버닝🌸 뉴비들을 위한! 이걸로 대체 되나요? 뉴비들이 🌷물어보는 ...,20,PT9M5S,11248,72,28
37,znHtKkHPvEQ,[메이플]하이퍼 버닝 🌸뉴비들을 위한! 재미 VS 체급? 본캐를 고를때💪 살펴봐야하...,20,PT8M45S,37865,105,113
38,Z9YUl3yQhxU,뉴비도 따라할 수 있도록 만들어봤습니다! 하이퍼버닝 최단시간 육성빌드,20,PT11M46S,375520,3500,568
39,TiyVva-odH0,"[메이플스토리] ""슈프림 유니온 랭커""가 엄선한「2025년 겨울 하이퍼버닝 직업 추...",20,PT20M47S,72827,250,187
40,Yd-UNV3RbfM,"완전 쌩 무자본 아델 육성 1화 (챌린저스 월드, 아이템 버닝, 하이퍼 버닝 MAX)",20,PT11M21S,107836,502,114
41,spAIOQ2nBZs,[한자] 2026년 여름 오버드라이브 하이퍼버닝 최종 직업추천 총정리!! (메잘알 ...,20,PT16M58S,111184,399,258
42,Dl6JGFAfczE,[메이플] 하이퍼 버닝에 '이 직업' 주면📈 100% 폐사합니다. 본캐 정하기 전🌸...,20,PT8M53S,28802,101,106
43,hkQYIrPbthM,"[메이플] 봄 소풍🌸 뉴비들을 위한! NO 아이템 버닝, NO 자본🧹 맨땅 캐릭터 ...",20,PT9M17S,37753,479,77
44,ep6YvyuVbV0,[메이플] 2026년 최신! 하이퍼 버닝🌸 뉴비들을 위한! 뉴비면 꼭 봐야하는📈 4...,20,PT24M6S,87568,436,148
45,Jw0QMbJDWm0,[한자] 하이퍼버닝 MAX 고효율 초고속 육성 방법 (25년 겨울 크라운 하이퍼버닝...,20,PT17M25S,170989,1996,294
46,f92dfu0biJI,260이후 메린이 해야할일 완벽정리.필수내실과 템세팅까지[메이플스토리],20,PT8M1S,356441,6026,558
47,HVSa7aqX5Tk,나로후닝의 2026 여름 직업 추천&평가,20,PT25M44S,279071,1072,506
48,4KtXVKyIBaM,[한자] 23주년 이벤트 직접 보여주는 공략 (하이퍼버닝 + 영구 자석펫 + 보약스...,20,PT18M14S,71914,487,290
49,SwkChr520Lg,「2026 최신 버전」메이플스토리 하버 직업 추천,20,PT7M47S,64690,179,61

### 3. Merge Search Results and Video Details

In [26]:
youtube_df = search_df.merge(video_df, on="video_id", how="left")
display(youtube_df)

,video_id,title,channel_title,published_at,description,video_title,category_id,duration,view_count,like_count,comment_count
0,mQo4xmzyIgY,[메이플] 하이퍼 버닝🌸 뉴비들을 위한! 아이템 버닝의 🐳한계는 있다?! 전투력 1...,잼이,2026-08-11T09:51:45Z,메이플 #메이플스토리 #잼이 #하이퍼버닝 #챌린저스 #아이템버닝 #여름방학 #겨울방...,[메이플] 하이퍼 버닝🌸 뉴비들을 위한! 아이템 버닝의 🐳한계는 있다?! 전투력 1...,20,PT8M28S,10217,88,55
1,1ArZ9wfeyqA,[메이플] 2026년 최신! 봄방학 🌸 뉴비들과 복귀 형님들을 위한🐧 하이퍼 버닝 ...,잼이,2026-03-18T08:18:12Z,메이플 #메이플스토리 #잼이 #하이퍼버닝 #챌린저스 #아이템버닝 #겨울방학 #크라운...,[메이플] 2026년 최신! 봄방학 🌸 뉴비들과 복귀 형님들을 위한🐧 하이퍼 버닝 ...,20,PT10M4S,120347,839,415
2,qc3mKB8uiSA,하이퍼버닝 단 1시간 컷 보여드리겠습니다,글자네,2025-10-02T08:35:23Z,항상 영상 사랑해주셔서 감사합니다! 세글자 팬카페 : https://cafe.nav...,하이퍼버닝 단 1시간 컷 보여드리겠습니다,20,PT14M47S,206692,845,95
3,6RGKFGjff3k,신직업 레테 하이퍼버닝 단 30분 컷 보여드리겠습니다,글자네,2026-06-21T09:15:26Z,항상 영상 사랑해주셔서 감사합니다! 세글자의 모든것 : https://linktr....,신직업 레테 하이퍼버닝 단 30분 컷 보여드리겠습니다,20,PT14M5S,155762,621,79
4,4aujILjlhkE,"필요 경험치가 반토막난 23주년 하버, 언제 어떻게 키워야할까?【메이플】",지명,2026-03-16T03:00:00Z,지명 #메이플 #23주년 #하이퍼버닝 지명 치지직 : https://chzzk.na...,"필요 경험치가 반토막난 23주년 하버, 언제 어떻게 키워야할까?【메이플】",20,PT7M15S,139680,1074,309
5,FMUmSNtWlEU,[메이플] 2026년 🐳여름방학! 하이퍼 버닝🌸 뉴비들을 위한! 맨땅 1렙부터📈 스...,잼이,2026-06-17T08:27:13Z,메이플 #메이플스토리 #잼이 #하이퍼버닝 #챌린저스 #아이템버닝 #여름방학 #겨울방...,[메이플] 2026년 🐳여름방학! 하이퍼 버닝🌸 뉴비들을 위한! 맨땅 1렙부터📈 스...,20,PT12M15S,84714,727,144
6,9b-cCrQyKYw,[한자] 하이퍼버닝 +하이퍼블링크 시작 전 마지막 점검!!! (놓치는 것 없이 세팅...,한자,2026-06-18T00:28:46Z,메이플스토리 하이퍼버닝 + 하이퍼블링크 완벽 가이드! 단 20~30분 만에 260레...,[한자] 하이퍼버닝 +하이퍼블링크 시작 전 마지막 점검!!! (놓치는 것 없이 세팅...,20,PT7M2S,53814,317,46
7,GeniNYE0V5M,[메이플] 2026년 최신! 하이퍼 버닝🌸 뉴비들을 위한! 고인물이 가르쳐 주지 않...,잼이,2026-08-05T12:16:03Z,메이플 #메이플스토리 #잼이 #하이퍼버닝 #챌린저스 #아이템버닝 #여름방학 #겨울방...,[메이플] 2026년 최신! 하이퍼 버닝🌸 뉴비들을 위한! 고인물이 가르쳐 주지 않...,20,PT8M13S,9593,123,40
8,ytnhqWf3_nQ,[메이플] 하이퍼 버닝 🌸 비수기 뉴비 유저들을 위한! 뉴비가 해야하는 🌷 270레...,잼이,2026-04-17T09:11:14Z,메이플 #메이플스토리 #잼이 #하이퍼버닝 #챌린저스 #아이템버닝 #겨울방학 #크라운...,[메이플] 하이퍼 버닝 🌸 비수기 뉴비 유저들을 위한! 뉴비가 해야하는 🌷 270레...,20,PT10M4S,50606,362,154
9,9saj1Kg7S1I,[메이플] 하이퍼 버닝 🌸 뉴비들을 위해서! 아이템 버닝 D-day 40 🐳 마지막...,잼이,2026-08-07T11:55:20Z,메이플 #메이플스토리 #잼이 #하이퍼버닝 #챌린저스 #아이템버닝 #여름방학 #겨울방...,[메이플] 하이퍼 버닝 🌸 뉴비들을 위해서! 아이템 버닝 D-day 40 🐳 마지막...,20,PT10M27S,19821,181,88
10,rEMZwLbgmcw,[메이플] 하이퍼 버닝 🌸뉴비들을 위해서! 챌린저스 D-day 50일! 남은 기간 ...,잼이,2026-07-29T10:18:59Z,메이플 #메이플스토리 #잼이 #하이퍼버닝 #챌린저스 #아이템버닝 #여름방학 #겨울방...,[메이플] 하이퍼 버닝 🌸뉴비들을 위해서! 챌린저스 D-day 50일! 남은 기간 ...,20,PT8M3S,31012,179,117
11,E10ZLrIvvLU,메이플스토리 하이퍼버닝 유튜버 동시 반응 + 자막,쵸코릴리,2022-06-15T10:11:29Z,"특정 유튜버에 대한 욕설, 비하, 모욕 등 부적절한 댓글은 삭제됩니다.",메이플스토리 하이퍼버닝 유튜버 동시 반응 + 자막,20,PT1M3S,370337,2277,265
12,QaxJ3yyFKLU,[메이플] 2026년 최신! 하이퍼 버닝🌸 뉴비들을 위한! 사람은 마음이 원동력💞 ...,잼이,2026-05-15T10:02:15Z,메이플 #메이플스토리 #잼이 #하이퍼버닝 #챌린저스 #아이템버닝 #여름방학 #겨울방...,[메이플] 2026년 최신! 하이퍼 버닝🌸 뉴비들을 위한! 사람은 마음이 원동력💞 ...,20,PT10M58S,29569,103,50
13,WD11kJwi7qk,[메이플] 여름방학 🐳 하이퍼 버닝🌸 뉴비들을 위한! 지금 챌섭해도 되나요? 늦게 ...,잼이,2026-07-17T08:41:29Z,메이플 #메이플스토리 #잼이 #하이퍼버닝 #챌린저스 #아이템버닝 #여름방학 #겨울방...,[메이플] 여름방학 🐳 하이퍼 버닝🌸 뉴비들을 위한! 지금 챌섭해도 되나요? 늦게 ...,20,PT9M43S,19677,202,49
14,hpCNPwUH3Xs,&quot;오직 성능으로만 뽑았습니다&quot; - 메이플 하이퍼버닝 직업 추천,도루,2025-12-16T10:05:04Z,메이플 메이플 하이퍼버닝 직업 추천.,"""오직 성능으로만 뽑았습니다"" - 메이플 하이퍼버닝 직업 추천",20,PT12M16S,186912,859,369
15,bvjkNF-9wGA,직업 선택하기 전 꼭 보세요. / 본인에게 잘 맞는 직업을 선택하는 방법,슈크림메이플,2026-06-11T09:34:21Z,메이플스토리 #하이퍼버닝 #직업선택 저는 미하일을 키우려는 메린이에여. ​ 왜 그런...,직업 선택하기 전 꼭 보세요. / 본인에게 잘 맞는 직업을 선택하는 방법,20,PT10M17S,50730,180,200
16,I_Xv18kwQOk,하이퍼버닝부스터 직업추천 TOP3. 유니온용 / 부캐용 각각 추천해드립니다,메이플 대장메린이,2025-08-24T03:00:31Z,출석보상으로 받는 하이퍼 버닝 부스터 사용할 직업 추천입니다 유니온용 TOP3와 보...,하이퍼버닝부스터 직업추천 TOP3. 유니온용 / 부캐용 각각 추천해드립니다,20,PT57S,182032,567,120
17,AZJBul4Yu28,서버선택 + 레벨업 + 템셋팅까지 모두 담았습니다! 2차 하이퍼버닝 육성 핵심 가이드,물다이아,2025-08-21T08:00:11Z,메이플 #하이퍼버닝 #물다이아 BGM 정보 로스트사가 - 큐브 블럭 타임라인 00:...,서버선택 + 레벨업 + 템셋팅까지 모두 담았습니다! 2차 하이퍼버닝 육성 핵심 가이드,20,PT15M14S,132593,1370,448
18,DjPrjex0M8o,[메이플] 잼이님 캐릭터가 🤖 빈 깡통입니다..하이퍼 버닝 MAX 부스터🔥 빈깡통 ...,잼이,2026-03-20T07:04:27Z,메이플 #메이플스토리 #잼이 #하이퍼버닝 #챌린저스 #아이템버닝 #겨울방학 #크라운...,[메이플] 잼이님 캐릭터가 🤖 빈 깡통입니다..하이퍼 버닝 MAX 부스터🔥 빈깡통 ...,20,PT9M43S,61608,476,175
19,nEgGNUhzcSY,하이퍼버닝 단 4시간 컷 보여드리겠습니다,글자네,2024-07-03T11:00:20Z,항상 영상 사랑해주셔서 감사합니다! 세글자 팬카페 : https://3gj.kr/ ...,하이퍼버닝 단 4시간 컷 보여드리겠습니다,20,PT11M6S,930919,3080,267
20,Q-b20FJZ0jQ,[메이플스토리 맑음] 챌린저스 월드 공략! (시즌4) / 260레벨 30분컷 빌드 ...,메이플스토리맑음,2026-06-17T05:05:10Z,챌린저스월드공략 #하이퍼버닝맥스 #챌린저스월드 #챌린저스월드3만점공략 #챌린저스월드...,[메이플스토리 맑음] 챌린저스 월드 공략! (시즌4) / 260레벨 30분컷 빌드 ...,20,PT28M34S,594141,5329,414
21,pgibyVx8B1E,하이퍼버닝 꿀직업들 모두 정리했습니다. 손해보기 싫으시다면 보세요.,슈크림메이플,2026-04-02T10:33:00Z,메이플스토리 #일리움 #렌 #와헌 #보마 #직업추천 #메이플스토리 이번 영상에서는 ...,하이퍼버닝 꿀직업들 모두 정리했습니다. 손해보기 싫으시다면 보세요.,20,PT10M12S,83155,212,252
22,ODlGzZkGAKw,제로 하이퍼 버닝 아직 할만해? (육성가이드라인),박서월,2024-12-16T21:30:02Z,AI로 자막달다보니 자막 오류가 만져도 조금씩 놓치네용 ㅠ 썸넬도 대충 하다 마는편...,제로 하이퍼 버닝 아직 할만해? (육성가이드라인),20,PT6M33S,66488,493,174
23,JnpdwKKke5Y,챌섭 국밥직업 4황 [메이플스토리 챌린저스월드 하이퍼버닝 추천직업],슈크림메이플,2026-05-23T02:15:56Z,메이플스토리 #챌린저스월드 #하이퍼버닝 메이플에서 새로운 직업을 키울때 가장 좋은것...,챌섭 국밥직업 4황 [메이플스토리 챌린저스월드 하이퍼버닝 추천직업],20,PT11M46S,47363,174,279
24,2W6Xpq_0WcM,[한자] 현재 하이퍼버닝 추천 직업과 비추천 직업 정리 (25년 12월 기준 챌섭 ...,한자,2025-12-11T07:16:56Z,하이하이 한자입니다~S2 이제 곧 하이퍼버닝 시즌이 옵니다 ㅎㅎ 항상 하는 그 고민...,[한자] 현재 하이퍼버닝 추천 직업과 비추천 직업 정리 (25년 12월 기준 챌섭 ...,20,PT8M45S,85768,207,173
25,le-wd0DnnVw,[메이플스토리] 너가 뭘 좋아할 지 몰라 전부 준비해봤어「2026년 여름 하이퍼버닝...,햄군 Youtube,2026-06-09T11:42:08Z,메이플스토리 #메이플 #하이퍼버닝 #직업추천 #렌 #보우마스터 #와일드헌터 #윈드브...,[메이플스토리] 너가 뭘 좋아할 지 몰라 전부 준비해봤어「2026년 여름 하이퍼버닝...,20,PT26M55S,79135,356,334
26,abNb5OJJQdw,[메이플] 2026년 최신! 하이퍼 버닝🌸 뉴비들을 위한! 사스케는 📈 웃고 있다...,잼이,2026-05-08T10:45:20Z,메이플 #메이플스토리 #잼이 #하이퍼버닝 #챌린저스 #아이템버닝 #여름방학 #겨울방...,[메이플] 2026년 최신! 하이퍼 버닝🌸 뉴비들을 위한! 사스케는 📈 웃고 있다...,20,PT9M39S,51407,135,83
27,rhFbqj9QPEY,찐 메린이분들도 따라하기 쉽도록 만들어보았습니다! 빠르게 육성하고 싶으시다면 따라하세요!,슈크림메이플,2026-06-21T05:58:05Z,챌린저스월드 #하이퍼버닝 #메이플스토리 이번 영상에서는 10레벨부터 280레벨까지 ...,찐 메린이분들도 따라하기 쉽도록 만들어보았습니다! 빠르게 육성하고 싶으시다면 따라하세요!,20,PT11M26S,49205,476,74
28,5C5DU2FiHZk,하이퍼버닝 직업 선택 전이라면 이 직업들 추천합니다 / 메이플스토리 직업추천,브하,2026-06-05T07:45:32Z,곧 있으면 메이플스토리의 하이퍼버닝이 시작됩니다. 이번엔 어떤 것을 키울지 정하셨나...,하이퍼버닝 직업 선택 전이라면 이 직업들 추천합니다 / 메이플스토리 직업추천,20,PT10M11S,64863,506,254
29,mMrZcNy4rxM,[메이플] 하이퍼 버닝 뉴비들을 위한! 잼이가 발로 해도 되는?! 쉬운 캐릭터 TOP 5,잼이,2026-05-27T11:50:59Z,메이플 #메이플스토리 #잼이 #하이퍼버닝 #챌린저스 #아이템버닝 #여름방학 #겨울방...,[메이플] 하이퍼 버닝 뉴비들을 위한! 잼이가 발로 해도 되는?! 쉬운 캐릭터 TOP 5,20,PT8M59S,20817,93,108
30,GHZjxf6SGGk,[메이플] 2026년 🌸 최신! 하이퍼 버닝 🌷 뉴비 필수 시청! 이거 안키우면 📈...,잼이,2026-04-06T08:31:04Z,메이플 #메이플스토리 #잼이 #하이퍼버닝 #챌린저스 #아이템버닝 #겨울방학 #크라운...,[메이플] 2026년 🌸 최신! 하이퍼 버닝 🌷 뉴비 필수 시청! 이거 안키우면 📈...,20,PT10M48S,51302,388,67
31,Mk8vWAocenE,어디서도 본 적 없는 하이퍼버닝 육성 꿀팁 [메이플],혜유안,2026-03-17T06:15:10Z,생방송 유튜브 https://www.youtube.com/@user-qh6js3nw...,어디서도 본 적 없는 하이퍼버닝 육성 꿀팁 [메이플],20,PT2M25S,31937,327,152
32,LwHvINCLuvI,[메이플] 하이퍼 버닝 🌸 뉴비들을 위한! 노말 메이린만 잡으면 된다? 챌린저스 📈...,잼이,2026-06-24T08:43:08Z,메이플 #메이플스토리 #잼이 #하이퍼버닝 #챌린저스 #아이템버닝 #여름방학 #겨울방...,[메이플] 하이퍼 버닝 🌸 뉴비들을 위한! 노말 메이린만 잡으면 된다? 챌린저스 📈...,20,PT10M35S,46541,395,138
33,Jg9xSIh9-ls,하이퍼버닝 사냥터부터 기초 템셋팅 방법까지 한번에! 메이플 챌린저스 월드 시즌4 핵...,물다이아,2026-06-14T00:00:37Z,챌섭 #챌린저스 #메이플 #물다이아 BGM 정보 로스트사가 - 큐브블럭 타임라인 0...,하이퍼버닝 사냥터부터 기초 템셋팅 방법까지 한번에! 메이플 챌린저스 월드 시즌4 핵...,20,PT18M10S,212336,3743,690
34,T61RzWvrU2g,직접 키워보고 추천하는 하이퍼 버닝 직업 추천! [메이플],혜유안,2025-12-12T06:49:35Z,생방송 유튜브 https://www.youtube.com/@user-qh6js3nw...,직접 키워보고 추천하는 하이퍼 버닝 직업 추천! [메이플],20,PT13M46S,82504,262,164
35,OgDvqNAM4ts,[메이플] 2026년 최신! 봄방학🌸 뉴비들을 위한! 하이퍼 버닝 🔥 MAX 캐릭터...,잼이,2026-03-23T09:05:54Z,메이플 #메이플스토리 #잼이 #하이퍼버닝 #챌린저스 #아이템버닝 #겨울방학 #크라운...,[메이플] 2026년 최신! 봄방학🌸 뉴비들을 위한! 하이퍼 버닝 🔥 MAX 캐릭터...,20,PT9M11S,56875,161,135
36,p8YeYncyJvc,[메이플] 하이퍼 버닝🌸 뉴비들을 위한! 이걸로 대체 되나요? 뉴비들이 🌷물어보는 ...,잼이,2026-05-29T11:33:48Z,메이플 #메이플스토리 #잼이 #하이퍼버닝 #챌린저스 #아이템버닝 #여름방학 #겨울방...,[메이플] 하이퍼 버닝🌸 뉴비들을 위한! 이걸로 대체 되나요? 뉴비들이 🌷물어보는 ...,20,PT9M5S,11248,72,28
37,znHtKkHPvEQ,[메이플]하이퍼 버닝 🌸뉴비들을 위한! 재미 VS 체급? 본캐를 고를때💪 살펴봐야하...,잼이,2026-05-25T11:33:25Z,메이플 #메이플스토리 #잼이 #하이퍼버닝 #챌린저스 #아이템버닝 #여름방학 #겨울방...,[메이플]하이퍼 버닝 🌸뉴비들을 위한! 재미 VS 체급? 본캐를 고를때💪 살펴봐야하...,20,PT8M45S,37865,105,113
38,Z9YUl3yQhxU,뉴비도 따라할 수 있도록 만들어봤습니다! 하이퍼버닝 최단시간 육성빌드,슈크림메이플,2025-06-22T11:06:42Z,메이플스토리 #하이퍼버닝 #260 #270 #사냥터 이번 영상에서는 부담없이 보면서...,뉴비도 따라할 수 있도록 만들어봤습니다! 하이퍼버닝 최단시간 육성빌드,20,PT11M46S,375520,3500,568
39,TiyVva-odH0,[메이플스토리] &quot;슈프림 유니온 랭커&quot;가 엄선한「2025년 겨울 ...,햄군 Youtube,2025-12-15T12:52:11Z,메이플스토리 #메이플 #하이퍼버닝 #직업추천 #팔라딘 #렌 #썬콜 #배틀메이지 #일...,"[메이플스토리] ""슈프림 유니온 랭커""가 엄선한「2025년 겨울 하이퍼버닝 직업 추...",20,PT20M47S,72827,250,187
40,Yd-UNV3RbfM,"완전 쌩 무자본 아델 육성 1화 (챌린저스 월드, 아이템 버닝, 하이퍼 버닝 MAX)",개구릿대,2025-12-19T05:45:02Z,무과금 육성기 레벨이 한번에 5씩 오르는 대박 메이플스토리 겨울방학 이벤트의 시작!...,"완전 쌩 무자본 아델 육성 1화 (챌린저스 월드, 아이템 버닝, 하이퍼 버닝 MAX)",20,PT11M21S,107836,502,114
41,spAIOQ2nBZs,[한자] 2026년 여름 오버드라이브 하이퍼버닝 최종 직업추천 총정리!! (메잘알 ...,한자,2026-06-17T03:08:16Z,"2026년 여름, '오버드라이브' 하이퍼버닝! 어떤 직업을 키울지 아직도 고민 중이...",[한자] 2026년 여름 오버드라이브 하이퍼버닝 최종 직업추천 총정리!! (메잘알 ...,20,PT16M58S,111184,399,258
42,Dl6JGFAfczE,[메이플] 하이퍼 버닝에 &#39;이 직업&#39; 주면📈 100% 폐사합니다. 본...,잼이,2026-04-29T10:50:49Z,메이플 #메이플스토리 #잼이 #하이퍼버닝 #챌린저스 #아이템버닝 #겨울방학 #크라운...,[메이플] 하이퍼 버닝에 '이 직업' 주면📈 100% 폐사합니다. 본캐 정하기 전🌸...,20,PT8M53S,28802,101,106
43,hkQYIrPbthM,"[메이플] 봄 소풍🌸 뉴비들을 위한! NO 아이템 버닝, NO 자본🧹 맨땅 캐릭터 ...",잼이,2026-04-01T08:35:28Z,메이플 #메이플스토리 #잼이 #하이퍼버닝 #챌린저스 #아이템버닝 #겨울방학 #크라운...,"[메이플] 봄 소풍🌸 뉴비들을 위한! NO 아이템 버닝, NO 자본🧹 맨땅 캐릭터 ...",20,PT9M17S,37753,479,77
44,ep6YvyuVbV0,[메이플] 2026년 최신! 하이퍼 버닝🌸 뉴비들을 위한! 뉴비면 꼭 봐야하는📈 4...,잼이,2026-06-08T14:37:07Z,메이플 #메이플스토리 #잼이 #하이퍼버닝 #챌린저스 #아이템버닝 #여름방학 #겨울방...,[메이플] 2026년 최신! 하이퍼 버닝🌸 뉴비들을 위한! 뉴비면 꼭 봐야하는📈 4...,20,PT24M6S,87568,436,148
45,Jw0QMbJDWm0,[한자] 하이퍼버닝 MAX 고효율 초고속 육성 방법 (25년 겨울 크라운 하이퍼버닝...,한자,2025-12-15T04:33:01Z,"이번 25년 겨울 '크라운' 하이퍼버닝, 챌린저스 월드에서 시작하시나요? 생성 보상...",[한자] 하이퍼버닝 MAX 고효율 초고속 육성 방법 (25년 겨울 크라운 하이퍼버닝...,20,PT17M25S,170989,1996,294
46,f92dfu0biJI,260이후 메린이 해야할일 완벽정리.필수내실과 템세팅까지[메이플스토리],메이플 대장메린이,2026-06-19T04:29:41Z,0:00 인트로 0:13 버닝비욘드 0:18 제네시스퀘스트 0:24 선행퀘스트 0:...,260이후 메린이 해야할일 완벽정리.필수내실과 템세팅까지[메이플스토리],20,PT8M1S,356441,6026,558
47,HVSa7aqX5Tk,나로후닝의 2026 여름 직업 추천&amp;평가,후닝,2026-06-10T08:00:04Z,메이플 #나로후닝 #직업추천 #하이퍼버닝 00:00 인트로 00:31 제논 04:2...,나로후닝의 2026 여름 직업 추천&평가,20,PT25M44S,279071,1072,506
48,4KtXVKyIBaM,[한자] 23주년 이벤트 직접 보여주는 공략 (하이퍼버닝 + 영구 자석펫 + 보약스...,한자,2026-03-15T20:57:53Z,3월 19일(목) 업데이트되는 23주년 이벤트! 랜선투어에서 예고했던 내용들이 인게...,[한자] 23주년 이벤트 직접 보여주는 공략 (하이퍼버닝 + 영구 자석펫 + 보약스...,20,PT18M14S,71914,487,290
49,SwkChr520Lg,「2026 최신 버전」메이플스토리 하버 직업 추천,페이지,2026-03-27T23:36:16Z,메이플 #하이퍼버닝 #직업추천 ▷ 구독과 좋아요는 제작자에게 큰 힘이 됩니다. ▷ ...,「2026 최신 버전」메이플스토리 하버 직업 추천,20,PT7M47S,64690,179,61

### 공식 API를 통한 데이터 수집 (AI 활용ver)
- (1) API 공식 문서 찾기 (+ API 키 발급)
- (2) AI에게 공식 문서 입력
    - URL 입력 (url 사이트 정보를 ai가 잘 가지고 올 수 있는 경우)
    - Text 복사/붙여넣기 (이미지 캡처해서 넣기)
- (3) 수집할 데이터 정보 제공
    - 어떤 유형의 데이터만 수집하고 싶은지 (응답 데이터 선별)
    - 얼마나 수집할지 (양)
- (4) 코드 파일을 생성할 경로와 .env파일 경로 제공

#### 추가
- 주석 달기
- 특정 라이브러리 사용 제한
    - ex. pandas 사용X

---

#### 대용량의 데이터를 안정적으로 수집을 하고 싶을 때
- (1) 중간 저장을 하는 로직 작성
    - 프로그램을 다시 실행했을 때, 저장한 데이터는 생략하고 이후의 데이터를 다시 수집하도록
- (2) 네트워크 장애시 재시도 로직 작성
    - ex. 최대 3번 지수백오프 방식으로 재시도

---
# GEMINI 활용

첨부해주신 주피터 노트북(ipynb) 코드를 검토해 본 결과, 
현재 코드는 특정 키워드로 영상을 검색(Search API)하고, 
해당 영상의 상세 정보(조회수, 좋아요 수 등 - Videos API)를 가져와 병합하는 부분까지만 작성되어 있습니다.

댓글과 대댓글을 추출하기 위해서는 유튜브의 CommentThreads API를 추가로 호출하는 과정이 필요합니다. 
기존 코드의 1~3단계를 그대로 유지한 상태에서, 
다음 단계(4단계, 5단계)로 댓글을 추출하고 CSV로 저장하는 코드를 덧붙여 수정 및 추가하시면 됩니다.

단계별 추가 및 수정 방법을 설명해 드리겠습니다.

1단계: 어떤 API가 필요한지 이해하기
댓글과 대댓글을 가져오기 위해서는 유튜브 공식 문서의 commentThreads 엔드포인트를 사용해야 합니다.
이 API는 영상의 최상위 댓글(Top-level comment)과 그 아래에 달린 대댓글(Replies)을 한 번에 가져올 수 있는 기능을 제공합니다.

2단계: 기존 코드 이어서 '댓글 수집' 셀 추가하기
기존 파일의 3. 영상 검색 정보와 상세 정보 데이터 병합 및 저장 코드 셀 아래에 새로운 코드 셀을 만들고 다음 코드를 입력하세요. 
1단계(검색 API)에서 구한 video_ids 리스트를 반복문으로 돌면서 댓글을 수집하는 로직입니다.

In [27]:
# 4. 영상별 댓글 및 대댓글 추출
import requests
import pandas as pd
from IPython.display import display

# CommentThreads API 엔드포인트
comment_url = 'https://www.googleapis.com/youtube/v3/commentThreads'
comments_list = []

print("댓글 수집을 시작합니다...")

# 1단계에서 구한 영상 ID 리스트(video_ids)를 순회
for video_id in video_ids:
    params = {
        'part': 'snippet,replies', # snippet(최상위 댓글), replies(대댓글)
        'videoId': video_id,
        'maxResults': 100,         # 한 번에 가져올 최대 댓글 수 (최대 100)
        'key': YOUTUBE_API_KEY,
        'textFormat': 'plainText'  # HTML 태그 없는 일반 텍스트로 추출
    }
    
    while True:
        try:
            response = requests.get(comment_url, params=params, timeout=30)
            
            # 댓글이 비활성화되어 있거나 권한이 없는 영상은 건너뜀
            if response.status_code != 200:
                print(f"비디오 ID {video_id}의 댓글을 가져올 수 없습니다. (상태 코드: {response.status_code})")
                break
                
            data = response.json()
            
            for item in data.get('items', []):
                # 1) 최상위 댓글 추출
                top_comment = item['snippet']['topLevelComment']['snippet']
                comments_list.append({
                    'video_id': video_id,
                    'comment_id': item['id'],
                    'parent_id': None, # 최상위 댓글이므로 부모 ID 없음
                    'author': top_comment.get('authorDisplayName'),
                    'text': top_comment.get('textDisplay'),
                    'like_count': top_comment.get('likeCount'),
                    'published_at': top_comment.get('publishedAt'),
                    'is_reply': False # 대댓글 여부
                })
                
                # 2) 대댓글 추출 (있는 경우)
                if 'replies' in item:
                    for reply in item['replies']['comments']:
                        reply_snippet = reply['snippet']
                        comments_list.append({
                            'video_id': video_id,
                            'comment_id': reply['id'],
                            'parent_id': item['id'], # 부모 댓글(최상위 댓글)의 ID
                            'author': reply_snippet.get('authorDisplayName'),
                            'text': reply_snippet.get('textDisplay'),
                            'like_count': reply_snippet.get('likeCount'),
                            'published_at': reply_snippet.get('publishedAt'),
                            'is_reply': True # 대댓글 여부
                        })
            
            # 다음 페이지가 있으면 pageToken 업데이트, 없으면 반복 종료 (Pagination)
            if 'nextPageToken' in data:
                params['pageToken'] = data['nextPageToken']
            else:
                break
                
        except Exception as e:
            print(f"에러 발생: {e}")
            break

# 리스트를 데이터프레임으로 변환
comments_df = pd.DataFrame(comments_list)
print(f"총 {len(comments_df)}개의 댓글 및 대댓글을 수집했습니다.")
display(comments_df.head())

댓글 수집을 시작합니다...
총 9712개의 댓글 및 대댓글을 수집했습니다.

,video_id,comment_id,parent_id,author,text,like_count,published_at,is_reply
0,mQo4xmzyIgY,UgyL6OjbK7M2DZ3ssN14AaABAg,None,@잼이,항상 감사합니다\n좋아요 댓글은 채널유지에 큰힘이 됩니다!\n\n0:21 전투력 1...,1,2026-08-11T09:52:10Z,False
1,mQo4xmzyIgY,UgxR91NeRQX5FDNafh54AaABAg,None,@조퇴,근대 지금 메이플 키워도 좋을까요?,0,2026-08-12T20:50:49Z,False
2,mQo4xmzyIgY,UgzJOcXRkzy6H3imR5F4AaABAg,None,@후려치기-v1b,저어 .. 응애인데요ㅠㅠ 하이퍼가 조금조금 성장하고보면 계속 스탯이 바뀌는데 그때마...,2,2026-08-11T18:55:20Z,False
3,mQo4xmzyIgY,UgzJOcXRkzy6H3imR5F4AaABAg.A_NmqFLEwDEA_Np-U1bWQ2,UgzJOcXRkzy6H3imR5F4AaABAg,@아무거나-g6k,보스가 안 깨지시거나 스펙업 수단이 없을 때만 해주시면 될 거예요!,2,2026-08-11T19:14:13Z,True
4,mQo4xmzyIgY,UgzJOcXRkzy6H3imR5F4AaABAg.A_NmqFLEwDEA_Ooag_1wU-,UgzJOcXRkzy6H3imR5F4AaABAg,@후려치기-v1b,​@아무거나-g6k네! 감사합니다 !!!!!!❤,0,2026-08-12T04:29:56Z,True

3단계: 추출한 데이터를 CSV 파일로 저장하기

마지막으로, 
위에서 만든 comments_df 데이터프레임을 csv 파일로 내보내는 코드를 작성합니다. 

한글 내용이 엑셀에서 깨지지 않게 하려면 encoding='utf-8-sig'를 반드시 넣어주어야 합니다.

In [28]:
# 5. 수집한 댓글 데이터를 CSV 파일로 저장
import os

# 저장할 파일명 지정
file_name = "youtube_comments_result.csv"

# CSV로 저장 (한글 깨짐 방지를 위해 utf-8-sig 인코딩 사용)
comments_df.to_csv(file_name, index=False, encoding='utf-8-sig')

# 파일이 저장된 현재 절대 경로 출력
print(f"파일 저장 완료! 경로: {os.path.abspath(file_name)}")

파일 저장 완료! 경로: c:\Users\Playdata\Desktop\김동석\파이썬 학습\enkoa-practice-python\내작업\day05_데이터수집\day05_데이터수집\데이터_수집_1_API_실습파일\youtube_comments_result.csv

요약: 코드 수정/추가 시 핵심 체크 포인트

API 호출 방식: 댓글은 [https://www.googleapis.com/youtube/v3/commentThreads](https://www.googleapis.com/youtube/v3/commentThreads) 주소로 호출해야 합니다.

part 파라미터: part='snippet,replies'로 설정해야 최상위 댓글(snippet)과 대댓글(replies)을 한 번에 받을 수 있습니다.

Pagination (페이징 처리): 영상 하나에 댓글이 100개가 넘을 경우 다음 페이지로 넘어가기 위해 nextPageToken을 처리하는 while True: 반복문이 들어가야 데이터 누락을 방지할 수 있습니다.

CSV 인코딩: 한국어 댓글이 포함되므로 to_csv 저장 시 encoding='utf-8-sig' 옵션을 꼭 넣어주세요.